name = "PhaseLockedLoops"
uuid = "61bba2ad-6888-4985-bf71-8cb2f28422dd"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.0.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"

[compat]
DSP = "0.7.8"
julia = "1.6"
